### ISSUE TITLE
TypeError: Cannot read property 'quotes' of undefined

### ISSUE THREAD

**Issue by CataForma** [johnwyles/hubot-quote-database#1]
Hello John,
I would like to use your script (could be very usefull for me) but I get an error when I try to run the command addquote text.

This is the error I'm getting:
```
[Fri Oct 06 2017 09:44:15 GMT+0300 (EEST)] INFO Connecting...
[Fri Oct 06 2017 09:44:26 GMT+0300 (EEST)] INFO Logged in as igaseebot of IBM CIO, but not yet connected
[Fri Oct 06 2017 09:44:27 GMT+0300 (EEST)] INFO Slack client now connected
[Fri Oct 06 2017 09:44:27 GMT+0300 (EEST)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
(node:24764) DeprecationWarning: sys is deprecated. Use util instead.
[Fri Oct 06 2017 09:44:28 GMT+0300 (EEST)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Fri Oct 06 2017 09:44:38 GMT+0300 (EEST)] ERROR TypeError: Cannot read property 'quotes' of undefined
  at TextListener.callback (/home/catalinformagiu/igasee/igabot/node_modules/hubot-quote-database/src/quote_database.coffee:74:7, <js>:25:47)
  at executeListener (/home/catalinformagiu/igasee/igabot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/catalinformagiu/igasee/igabot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/catalinformagiu/igasee/igabot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/catalinformagiu/igasee/igabot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/catalinformagiu/igasee/igabot/node_modules/async/lib/async.js:268:15)
  at /home/catalinformagiu/igasee/igabot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

Any idea what I did wrong and how can I fix this?

Thank you in advance.

**Comment by CataForma** [comment]
Hello again,
sorry it seem that it was my fault and now the bot works fine with your script.
I have a question: is it possible to save all the quote's you add to the bot? Because right now after restart the bot doesn't "remember" any quote.

**Comment by johnwyles** [comment]
the database should use a datastore (brain) which is either persistent store or redis store as i recall - that is based on your settings for your "brain"

**Comment by johnwyles** [comment]
https://github.com/changhaitravis/hubot-postgres-brain
